global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'product_service'
    metrics_path: /metrics
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:9090']
