name: Go CI/Build
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Go version
        id: go-version
        run: |
          echo "GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV
          echo "Go version: $GO_VERSION"

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Format Go
        run: |
          gofmt -s -w .
          git diff --exit-code
      - name: Vet Go
        run: go vet ./...
      - name: Tidy Modules
        run: go mod tidy --diff
      - name: Verify Modules
        run: go mod verify
      - name: Build Code
        run: go build -o /dev/null ./...
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck -test ./...
      - name: Run unit tests
        run: |
          go test -v -count=1 -race -shuffle=0 -coverprofile=coverage.txt ./internal/...
          go tool cover -html=coverage.txt -o coverage.html
      - name: Upload Test Coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: coverage.html


