name: Integration Tests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main

jobs:

  run-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Go version
        id: go-version
        run: |
          echo "GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV
          echo "Go version: $GO_VERSION"

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Docker Compose
        run: |
          docker compose version
          cp example.env .env
          GO_VERSION=${{ env.GO_VERSION }} docker compose up -d --build

      - name: Check postgres logs
        run: docker compose logs postgres

      - name: Run Integration Tests
        run: |
          ENV_PATH=example.env go test -v -count=10 -parallel=5 -race -shuffle=on ./integration/...
          


